Analyzing weekly transaction data for a small company.

In [3]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

In [7]:
revenues = [120, 250, 80, 310, 95]
revenues_with_tax=[]

for r in revenues:
    revenues_with_tax.append(r * (1 + tax_rate))

print(revenues_with_tax)
print(revenues)

[141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]
[120, 250, 80, 310, 95]

In [9]:
revenues = [120, 250, 80, 310, 95]
final_revenues=[]

for r in revenues:
    final_revenues.append(r * (1 + tax_rate)* (1 - discount_rate))

print(final_revenues)

[127.44, 265.5, 84.96, 329.21999999999997, 100.89]

In [11]:
revenues = [120, 250, 80, 310, 95]

greater_than_100 = []

for r in revenues:
    greater_than_100.append(r > 100)
    
print(greater_than_100)

[True, True, False, True, False]

In [12]:
revenues = [120, 250, 80, 310, 95]

greater_than_100 = []

for r in revenues:
    greater_than_100.append(r > 100 and r < 300)
    
print(greater_than_100)

[True, True, False, False, False]

Parentheses define the order of calculations in Python.

In [13]:
sales = [120, 250, 80, 310, 95]

In [17]:
sales = [120, 250, 80, 310, 95]
total =0

for s in sales:
    total=total + s
    
print(total)

855

In [20]:
sales = [120, 250, 80, 310, 95]

total = 0

for s in sales:
    total=total + s

average = total / len(sales)

print(average)

171.0

In [21]:
sales = [120, 250, 80, 310, 95]

maximum = sales[0]

for s in sales:
    if s > maximum:
        maximum = s

print(maximum)

310

In [25]:
sales = [120, 250, 80, 310, 95]
greater_than_150 =[]

for s in sales:
    if s > 150:
        greater_than_150.append(s)
    
print(len(greater_than_150))

2

In [ ]:
sales = [120, 250, 80, 310, 95]
new_sales=[]

for s in sales:
    new_sales.append(s + (s*0.05))

print(new_sales)

[126.0, 262.5, 84.0, 325.5, 99.75]

“Premium” if revenue > 250
“Standard” if 100 < revenue ≤ 250
“Low” otherwise

In [ ]:
sales = [120, 250, 80, 310, 95]
segments=[]

for s in sales:
    if s > 250:
        segments.append("Premium")
    elif 100 < s <= 250:
        segments.append("Standard")
    else:
        segments.append("Low")

print(segments)

['Standard', 'Standard', 'Low', 'Premium', 'Low']

In [32]:
sales = [120, 250, 80, 310, 95]
segments=[]

for s in sales:
    if s > 250:
        segments.append("Premium")
    elif 100 < s <= 250:
        segments.append("Standard")
    else:
        segments.append("Low")

print("Premium", segments.count("Premium"))
print("Standard:", segments.count("Standard"))
print("Low:", segments.count("Low"))

Premium 1
Standard: 2
Low: 2

elif condition is evaluated from top to bottom, and Python stops at the first condition that is True.

This means the order directly affects the result.

In [33]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]

In [36]:
unique_ids= set(customer_ids)

print(unique_ids)

{1, 2, 3, 4, 5, 6}

In [37]:
l = list(unique_ids)

print(l)

[1, 2, 3, 4, 5, 6]

In [39]:
original_length = len(customer_ids)
new_length = len(l)

print(original_length)
print(new_length)

8
6

Sets are unordered because they store elements based on hashing, not position, so no fixed order is maintained.

In [40]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}

In [49]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}

if customer["revenue"] > 250:
    customer["segment"] = "Premium"
elif 100 < customer["revenue"] <= 250:
    customer["segment"] = "Standard"
else:
    customer["segment"] = "Low"
    
print(customer["segment"])

Standard

In [52]:
customer["revenue"] = 300

if customer["revenue"] > 250:
    customer["segment"] = "Premium"
elif 100 < customer["revenue"] <= 250:
    customer["segment"] = "Standard"
else:
    customer["segment"] = "Low"
    
print(customer["segment"])

Premium

In [56]:
customer.pop("city")

'Yerevan'

In [58]:
for key, value in customer.items():
    print(key,"-", value)

name - Anna
revenue - 300
segment - Premium

Dictionaries are useful because they store data in key–value pairs, making it easy to organize and access related information.

In [59]:
revenues = [120, 250, 80, 310, 95]

taxed_revenues = [r * 0.9 for r in revenues]
print(taxed_revenues)

[108.0, 225.0, 72.0, 279.0, 85.5]

In [60]:
greater_100 = [r for r in revenues if r > 100]
print(greater_100)

[120, 250, 310]

In [61]:
labels = ["High" if r > 200 else "Normal" for r in revenues]
print(labels)

['Normal', 'High', 'Normal', 'High', 'Normal']

 list comprehension for clean transformations and filtering.
 
 loops when logic becomes complex, conditional, or multi-step.

In [63]:
import pandas as pd

data = {
    "revenue": revenues
}

df = pd.DataFrame(data)
df

   revenue
0      120
1      250
2       80
3      310
4       95

In [64]:
df["revenue_after_tax"] = df["revenue"] * (1 + tax_rate)
df

   revenue  revenue_after_tax
0      120              141.6
1      250              295.0
2       80               94.4
3      310              365.8
4       95              112.1

In [65]:
filtered_df = df[df["revenue"] > 100]
filtered_df

   revenue  revenue_after_tax
0      120              141.6
1      250              295.0
3      310              365.8

In [66]:
df = df.drop(columns=["revenue_after_tax"])
df

   revenue
0      120
1      250
2       80
3      310
4       95

In [67]:
df.shape

(5, 1)

Using conditional logic in Pandas allows you to transform and categorize data efficiently based on rules, without writing explicit loops.