In [ ]:
import keras

### Arithmetic Operations

In [2]:
r = 1500
t = 0.2


total = r * (1 + t)

total

1800.0

In [3]:
2!=3

True

In [5]:
2==3

False

In [7]:
(10>5) or (10<5)

True

### List

In [9]:
l = [10,20,30,40]
l

[10, 20, 30, 40]

In [10]:
l.append(50)

In [11]:
l

[10, 20, 30, 40, 50]

In [12]:
l = ['data1.csv', 'data2.csv', 'data3.csv']

In [20]:
len(l[1]) - len(l[2])

0

### Tuple

In [21]:
t = (10, 12, 13)

In [22]:
t

(10, 12, 13)

### Set

In [23]:
my_list=[1, 2, 3, 4, 5,5,5,5,5]

In [26]:
my_set = set(my_list)
my_set

{1, 2, 3, 4, 5}

In [28]:
new_l= list(my_set)
new_l

[1, 2, 3, 4, 5]

In [29]:
a = {1,2,3,4,5}
b = {4,5,6,7,8}
a.intersection(b)

{4, 5}

### Dictionary

In [30]:
# key value pairs
customers = {
             'Alice': 25, 
             'Bob': 30, 
             'Charlie': 35,
             'Charlie': 31,
             'Charlie': [32,2]
             }

In [31]:
customers

{'Alice': 25, 'Bob': 30, 'Charlie': [32, 2]}

In [32]:
customers['Alice'] = 30

In [33]:
customers

{'Alice': 30, 'Bob': 30, 'Charlie': [32, 2]}

In [35]:
customer = {'name': 'Alice', 'age': 30, 'city': 'New York'}
customer['State'] = 'NY'
customer['Segment'] = 'Premium'

In [36]:
customer1 = customer
customer1

{'name': 'Alice',
 'age': 30,
 'city': 'New York',
 'State': 'NY',
 'Segment': 'Premium'}

In [37]:
# Bob
customer2 = {'name': 'Bob', 'age': 25, 'city': 'Los Angeles', 'State': 'CA', 'Segment': 'Standard'}
# Armen
customer3 = {'name': 'Armen', 'age': 28, 'city': 'Chicago', 'State': 'IL'}

In [38]:
list_of_customers = [customer1, customer2, customer3]
list_of_customers

[{'name': 'Alice',
  'age': 30,
  'city': 'New York',
  'State': 'NY',
  'Segment': 'Premium'},
 {'name': 'Bob',
  'age': 25,
  'city': 'Los Angeles',
  'State': 'CA',
  'Segment': 'Standard'},
 {'name': 'Armen', 'age': 28, 'city': 'Chicago', 'State': 'IL'}]

### Pandas

In [39]:
import pandas as pd
import numpy as np

In [41]:
data = {'name': ['Alice', 'Bob', 'Charlie','David','Armen'], 
        'age': [30, 25, 28, 35, 42], 
        'city': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'San Francisco'],
        'revenue': [10000, 15000, 12000, 20000, 18000],
        'segment': ['Premium', 'Premium', 'Premium', 'Standard', 'Premium']}

In [42]:
df = pd.DataFrame(data)
df.head()

      name  age           city  revenue   segment
0    Alice   30       New York    10000   Premium
1      Bob   25    Los Angeles    15000   Premium
2  Charlie   28        Chicago    12000   Premium
3    David   35         Boston    20000  Standard
4    Armen   42  San Francisco    18000   Premium

In [46]:
df.loc[df["revenue"] > 12000,"segment"] = "High Revenue"

df

      name  age           city  revenue       segment
0    Alice   30       New York    10000       Premium
1      Bob   25    Los Angeles    15000  High Revenue
2  Charlie   28        Chicago    12000       Premium
3    David   35         Boston    20000  High Revenue
4    Armen   42  San Francisco    18000  High Revenue

### IF Statement

In [54]:
revenue = 101

if revenue > 100:
    print("High revenue")
    print(f"Because the revenue is: {revenue}")
    
else:
    print("Low Revenue")

print("Analysis complete")

High revenue
Because the revenue is: 101
Analysis complete

In [55]:
revenue = 100

if revenue > 200:
    print(f"Very high revenue: {revenue}")
elif revenue > 100:
    print(f"High revenue: {revenue}")
elif revenue > 50:
    print(f"Medium revenue: {revenue}")
else:
    print(f"Low revenue: {revenue}")

Medium revenue: 100

In [56]:
is_active = False


if is_active:
    print('Okay')

### Bolean

In [57]:
revenue = 90
is_active = False

if revenue > 100 or is_active:
    print("Target customer")

In [58]:
is_active = False
if not is_active:
    print("Customer is active")

Customer is active

In [59]:
revenue = 100

if revenue == 100:
    print('Revenue is 100')
    if is_active:
        print('Great')
    else:
        print('Bad')
else:
    print('reveneu is not 100')

Revenue is 100
Bad

### Loops

In [61]:
sales = [10,20,30,40,50,84,0,212]

sales[0] = sales[0]*2
sales[1] = sales[1]*2
sales[2] = sales[2]*2
sales[3] = sales[3]*2
sales[4] = sales[4]*2

In [72]:
new_sales =[]

for i in sales:
    new_sales.append(i * 2)
    
new_sales

[40, 80, 120, 160, 200, 168, 0, 424]

In [74]:
# or
new_sales=[i * 2 for i in sales]

new_sales

[40, 80, 120, 160, 200, 168, 0, 424]

### List Comprehentions

In [75]:
l = [10,20,20,0]

l_1 = [i for i in l if i>0]
l_0 = [i for i in l if i==0]

l_0

[0]

In [76]:
["Champion" if value>0 else "Loser" for value in l]

['Champion', 'Champion', 'Champion', 'Loser']