In [1]:
## Unzipping File
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:   
    zip_ref.extractall("../data/raw/")

In [2]:
## Import packages
import pandas as pd

In [3]:
df_orders = pd.read_csv('../data/raw/orders.csv')
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [4]:
df_orders.tail()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [5]:
df_orders.shape

(3421083, 7)

In [6]:
print(f"""
tha shape of the data: {df_orders.shape}
number of rows: {df_orders.shape[0]}
number of columns: {df_orders.shape[1]}
""")

tha shape of the data: (3421083, 7)
number of rows: 3421083
number of columns: 7

In [7]:
df_orders_new = df_orders.rename(columns={"eval_set": "dataset_type"})
df_orders_new.head()

,order_id,user_id,dataset_type,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [8]:
df_orders.rename(columns={"eval_set" : "dataset_type"})

,order_id,user_id,dataset_type,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

In [9]:
df_orders.drop(columns = ['eval_set'])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [10]:
df_orders.dtypes

order_id                    int64
user_id                     int64
eval_set                      str
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [11]:
df_products =pd.read_csv("../data/raw/products.csv")
df_products.head(10)

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3
5,6,Dry Nose Oil,11,11,2.6
6,7,Pure Coconut Water With Orange,98,7,4.4
7,8,Cut Russet Potatoes Steam N' Mash,116,1,1.1
8,9,Light Strawberry Blueberry Yogurt,120,16,7.0
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4

In [12]:
df_products.tail()

,product_id,product_name,aisle_id,department_id,prices
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3
49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.1
49690,49686,Artisan Baguette,112,3,7.8
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.7
49692,49688,Fresh Foaming Cleanser,73,11,13.5

In [13]:
df_products.columns

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices'], dtype='str')

In [14]:
df_products.info

<bound method DataFrame.info of        product_id                                       product_name  \
0               1                         Chocolate Sandwich Cookies
1               2                                   All-Seasons Salt
2               3               Robust Golden Unsweetened Oolong Tea
3               4  Smart Ones Classic Favorites Mini Rigatoni Wit...
4               5                          Green Chile Anytime Sauce
...           ...                                                ...
49688       49684          Vodka, Triple Distilled, Twist of Vanilla
49689       49685                 En Croute Roast Hazelnut Cranberry
49690       49686                                   Artisan Baguette
49691       49687         Smartblend Healthy Metabolism Dry Cat Food
49692       49688                             Fresh Foaming Cleanser

       aisle_id  department_id  prices
0            61             19     5.8
1           104             13     9.3
2            94              7     4.5
3            38              1    10.5
4             5             13     4.3
...         ...            ...     ...
49688       124              5     5.3
49689        42              1     3.1
49690       112              3     7.8
49691        41              8     4.7
49692        73             11    13.5

[49693 rows x 5 columns]>

In [15]:
df_products.dtypes

product_id         int64
product_name         str
aisle_id           int64
department_id      int64
prices           float64
dtype: object

In [16]:
df_products.describe()

         product_id      aisle_id  department_id        prices
count  49693.000000  49693.000000   49693.000000  49693.000000
mean   24844.345139     67.770249      11.728433      9.994136
std    14343.717401     38.316774       5.850282    453.519686
min        1.000000      1.000000       1.000000      1.000000
25%    12423.000000     35.000000       7.000000      4.100000
50%    24845.000000     69.000000      13.000000      7.100000
75%    37265.000000    100.000000      17.000000     11.200000
max    49688.000000    134.000000      21.000000  99999.000000

In [17]:
df_products.drop(columns =['aisle_id'])

,product_id,product_name,department_id,prices
0,1,Chocolate Sandwich Cookies,19,5.8
1,2,All-Seasons Salt,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,1,10.5
4,5,Green Chile Anytime Sauce,13,4.3
...,...,...,...,...
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",5,5.3
49689,49685,En Croute Roast Hazelnut Cranberry,1,3.1
49690,49686,Artisan Baguette,3,7.8
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,8,4.7
49692,49688,Fresh Foaming Cleanser,11,13.5

In [18]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [19]:
df_products.new= df_products.drop(columns =['aisle_id'])
df_products.new

C:\Users\User\AppData\Local\Temp\ipykernel_2504\3962548709.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_products.new= df_products.drop(columns =['aisle_id'])

,product_id,product_name,department_id,prices
0,1,Chocolate Sandwich Cookies,19,5.8
1,2,All-Seasons Salt,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,1,10.5
4,5,Green Chile Anytime Sauce,13,4.3
...,...,...,...,...
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",5,5.3
49689,49685,En Croute Roast Hazelnut Cranberry,1,3.1
49690,49686,Artisan Baguette,3,7.8
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,8,4.7
49692,49688,Fresh Foaming Cleanser,11,13.5

In [21]:
df_products_new = df_products.assign(
    is_high = df_products["prices"] > 8 ,
    is_low = df_products["prices"] < 8
)

In [24]:
df_products.head()
df_products_new

,product_id,product_name,aisle_id,department_id,prices,is_high,is_low
0,1,Chocolate Sandwich Cookies,61,19,5.8,False,True
1,2,All-Seasons Salt,104,13,9.3,True,False
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,False,True
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,True,False
4,5,Green Chile Anytime Sauce,5,13,4.3,False,True
...,...,...,...,...,...,...,...
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3,False,True
49689,49685,En Croute Roast Hazelnut Cranberry,42,1,3.1,False,True
49690,49686,Artisan Baguette,112,3,7.8,False,True
49691,49687,Smartblend Healthy Metabolism Dry Cat Food,41,8,4.7,False,True
49692,49688,Fresh Foaming Cleanser,73,11,13.5,True,False

In [25]:
df_departments = pd.read_csv("../data/raw/departments.csv")
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [26]:
df_departments.T

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [27]:
df_dep_t = df_departments.T

In [28]:
df_dep_t.reset_index(inplace=True)

In [29]:
new_header = df_dep_t.iloc[0]

In [30]:
df_dep_t_new = df_dep_t[1:]

In [31]:
df_dep_t_new.columns = new_header   

df_dep_t_new.head()

0 department_id department
1             1     frozen
2             2      other
3             3     bakery
4             4    produce
5             5    alcohol