## Exploring

In [1]:
import pandas as pd

In [2]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [3]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [4]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [5]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [6]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

### Orders

In [7]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [8]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 198.9 MB

In [9]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [10]:
pd.options.display.float_format = '{:,.2f}'.format
df_orders[["order_hour_of_day" ,"days_since_prior_order"]].describe()

       order_hour_of_day  days_since_prior_order
count       3,421,083.00            3,214,874.00
mean               13.45                   11.11
std                 4.23                    9.21
min                 0.00                    0.00
25%                10.00                    4.00
50%                13.00                    7.00
75%                16.00                   15.00
max                23.00                   30.00

In [11]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [12]:
df_orders["order_id"].nunique()

3421083

In [13]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.00
2,473747,1,prior,3,3,12,21.00
3,2254736,1,prior,4,4,7,29.00
4,431534,1,prior,5,4,15,28.00

In [14]:
df_orders["user_id"].nunique()

206209

In [15]:
df_orders["eval_set"].value_counts(dropna=False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [16]:
df_orders["order_dow"].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [17]:
df_orders["order_hour_of_day"].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [18]:
df_orders["days_since_prior_order"].isna().sum()

np.int64(206209)

In [19]:
df_orders.loc[df_orders["order_number"] ==1 , "days_since_prior_order"].isna().all()

np.True_

In [20]:
df_orders["order_id"].is_unique

True

In [21]:
df_orders["order_dow"].between(0,6).all()

np.True_

In [22]:
df_orders["order_hour_of_day"].between(0, 23).all()

np.True_

In [23]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [24]:
df_orders_train.drop(columns=["eval_set"])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,11,4,8,14.00
25,1492625,2,15,1,11,30.00
49,2196797,5,5,0,11,6.00
74,525192,7,21,2,11,6.00
78,880375,8,4,1,14,10.00
...,...,...,...,...,...,...
3420838,2585586,206199,20,2,16,30.00
3420862,943915,206200,24,6,19,6.00
3420924,2371631,206203,6,4,19,30.00
3420933,1716008,206205,4,1,16,10.00
3421082,272231,206209,14,6,14,30.00

In [25]:
del df_orders

### Products_train

In [26]:
df_orders_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [27]:
df_orders_products_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           1384617 non-null  int64
 1   product_id         1384617 non-null  int64
 2   add_to_cart_order  1384617 non-null  int64
 3   reordered          1384617 non-null  int64
dtypes: int64(4)
memory usage: 42.3 MB

In [28]:
df_orders_products_train.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [29]:
df_orders_products_train.describe()

          order_id   product_id  add_to_cart_order    reordered
count 1,384,617.00 1,384,617.00       1,384,617.00 1,384,617.00
mean  1,706,297.62    25,556.24               8.76         0.60
std     989,732.65    14,121.27               7.42         0.49
min           1.00         1.00               1.00         0.00
25%     843,370.00    13,380.00               3.00         0.00
50%   1,701,880.00    25,298.00               7.00         1.00
75%   2,568,023.00    37,940.00              12.00         1.00
max   3,421,070.00    49,688.00              80.00         1.00

In [30]:
df_orders_products_train.isna().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [31]:
df_orders_products_train.value_counts().sum()

np.int64(1384617)

In [32]:
len(df_orders_products_train)

1384617

In [33]:
df_orders_products_train["order_id"].nunique()

131209

In [34]:
df_orders_products_train["reordered"].value_counts(dropna=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [35]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [36]:
df_orders_products_train["reordered"].isin([0, 1]).all()

np.True_

### Products

In [37]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [38]:
df_products.dtypes

product_id         int64
product_name         str
aisle_id           int64
department_id      int64
prices           float64
dtype: object

In [39]:
df_products["prices"].describe()

count   49,693.00
mean         9.99
std        453.52
min          1.00
25%          4.10
50%          7.10
75%         11.20
max     99,999.00
Name: prices, dtype: float64

In [40]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 3.4 MB

In [41]:
df_products.isna().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [42]:
df_products.isna().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [43]:
df_products["product_id"].nunique()

49686

In [44]:
df_products["product_id"].is_unique

False

In [45]:
df_products["department_id"].nunique()

21

In [46]:
df_products["aisle_id"].nunique()

134

In [47]:
df_products["product_name"].duplicated().sum()

np.int64(20)

### departments_t

In [48]:
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [49]:
df_departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 638.0 bytes

In [50]:
df_departments["department_id"].is_unique

True

In [51]:
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

In [52]:
df_departments["department"].nunique()

21

In [53]:
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

### aisles

In [54]:
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [55]:
df_aisles.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    str
dtypes: int64(1), str(1)
memory usage: 4.2 KB

In [56]:
df_aisles.dtypes

aisle_id    int64
aisle         str
dtype: object

In [57]:
df_aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64

In [58]:
df_aisles["aisle"].nunique()

134

In [59]:
df_aisles["aisle"].isna().sum()

np.int64(0)

## Merge()

pd.merge(left_df, right_df, on="key_column", how="left")

In [60]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on ="department_id",
    how="left"
)
df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

In [61]:
df_products_departments_check = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left",
    indicator=True
)

df_products_departments_check.head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,both
1,2,All-Seasons Salt,104,13,9.30,pantry,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,both
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,both

In [62]:
df_products_departments_check["_merge"].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [63]:
df_products_departments_check[
    df_products_departments_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices, department, _merge]
Index: []

In [64]:
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

In [65]:
df_products_departments["department"].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [78]:
df_products_departments["department"].value_counts().head(1)

department
personal care    6565
Name: count, dtype: int64

In [79]:
df_products_departments['department'].value_counts(normalize=True).head

<bound method NDFrame.head of department
personal care     0.13
snacks            0.13
pantry            0.11
beverages         0.09
frozen            0.08
dairy eggs        0.07
household         0.06
canned goods      0.04
dry goods pasta   0.04
produce           0.03
bakery            0.03
deli              0.03
missing           0.03
international     0.02
breakfast         0.02
babies            0.02
alcohol           0.02
pets              0.02
meat seafood      0.02
other             0.01
bulk              0.00
Name: proportion, dtype: float64>

In [82]:
df_products_departments['department'].nunique()

21

In [83]:
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on = 'aisle_id',
    how = 'left'
)

df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,marinades meat preparation

In [88]:
df_products_aisles_check = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left",
    indicator=True
)

df_products_aisles_check["_merge"].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [89]:
df_products_aisles_check[
    df_products_aisles_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices, department, aisle, _merge]
Index: []

In [90]:
print(df_products.shape)
print(df_products_departments.shape)
print(df_products_enriched.shape)

(49693, 5)
(49693, 6)
(49693, 7)

In [91]:
df_departments['department_id'].is_unique

True

In [92]:
df_aisles["aisle_id"].is_unique

True

In [95]:
df_products_enriched["aisle"].value_counts()

aisle
missing                         1258
candy chocolate                 1246
ice cream ice                   1091
vitamins supplements            1038
yogurt                          1026
                                ...
frozen juice                      47
baby accessories                  44
packaged produce                  32
bulk grains rice dried goods      26
bulk dried fruits vegetables      12
Name: count, Length: 134, dtype: int64

In [94]:
df_products_departments["department"].value_counts()

department
personal care      6565
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3449
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1116
babies             1081
alcohol            1056
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [97]:
df_products_enriched["aisle"].value_counts().head(10)

aisle
missing                 1258
candy chocolate         1246
ice cream ice           1091
vitamins supplements    1038
yogurt                  1026
chips pretzels           989
tea                      894
packaged cheese          891
frozen meals             880
cookies cakes            874
Name: count, dtype: int64

In [102]:
df_products_enriched[["department", "aisle"]].drop_duplicates()["department"].value_counts()

department
personal care      17
pantry             12
snacks             11
frozen             11
dairy eggs         10
household          10
beverages           8
meat seafood        7
dry goods pasta     5
canned goods        5
produce             5
deli                5
alcohol             5
bakery              5
babies              4
breakfast           4
international       4
pets                2
bulk                2
missing             1
other               1
Name: count, dtype: int64

In [103]:
df_products_enriched[["department", "aisle"]].drop_duplicates().head(20)

         department                          aisle
0            snacks                  cookies cakes
1            pantry              spices seasonings
2         beverages                            tea
3            frozen                   frozen meals
4            pantry     marinades meat preparation
5     personal care               cold flu allergy
6         beverages                  juice nectars
7            frozen                 frozen produce
8        dairy eggs                         yogurt
9         beverages  water seltzer sparkling water
10        beverages                   refrigerated
11           frozen                 frozen dessert
13        household                dish detergents
14           babies                  diapers wipes
15           snacks             ice cream toppings
16     meat seafood                poultry counter
17           frozen                   frozen pizza
18  dry goods pasta        grains rice dried goods
20             pets                  dog food care
21    personal care                   oral hygiene

In [104]:
pd.crosstab (
    df_products_enriched['department'],
    df_products_enriched['aisle']
)

aisle,air fresheners candles,asian foods,baby accessories,baby bath body care,baby food formula,bakery desserts,baking ingredients,baking supplies decor,beauty,beers coolers,...,spreads,tea,tofu meat alternatives,tortillas flat bread,trail mix snack mix,trash bags liners,vitamins supplements,water seltzer sparkling water,white wines,yogurt
department,,,,,,,,,,,,,,,,,,,,,
alcohol,0,0,0,0,0,0,0,0,0,387,...,0,0,0,0,0,0,0,0,147,0
babies,0,0,44,132,718,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bakery,0,0,0,0,0,297,0,0,0,0,...,0,0,0,241,0,0,0,0,0,0
beverages,0,0,0,0,0,0,0,0,0,0,...,0,894,0,0,0,0,0,344,0,0
breakfast,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bulk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
canned goods,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dairy eggs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1026
deli,0,0,0,0,0,0,0,0,0,0,...,0,0,159,0,0,0,0,0,0,0
dry goods pasta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
frozen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
household,355,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,112,0,0,0,0
international,0,605,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
meat seafood,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
missing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
other,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pantry,0,0,0,0,0,0,623,290,0,0,...,493,0,0,0,0,0,0,0,0,0
personal care,0,0,0,0,0,0,0,0,178,0,...,0,0,0,0,0,0,1038,0,0,0
pets,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
produce,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
snacks,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,69,0,0,0,0,0

In [105]:
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [106]:
df_orders_products_train

         order_id  product_id  add_to_cart_order  reordered
0               1       49302                  1          1
1               1       11109                  2          1
2               1       10246                  3          0
3               1       49683                  4          0
4               1       43633                  5          1
...           ...         ...                ...        ...
1384612   3421063       14233                  3          1
1384613   3421063       35548                  4          1
1384614   3421070       35951                  1          1
1384615   3421070       16953                  2          1
1384616   3421070        4724                  3          1

[1384617 rows x 4 columns]

In [108]:
df_train_transactions = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on= 'order_id',
    how= 'left'
)
df_train_transactions.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.00,196,1,1
1,1187899,1,train,11,4,8,14.00,25133,2,1
2,1187899,1,train,11,4,8,14.00,38928,3,1
3,1187899,1,train,11,4,8,14.00,26405,4,1
4,1187899,1,train,11,4,8,14.00,39657,5,1

In [112]:
df_train_transactions_check = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left",
    indicator=True
)

# df_train_transactions_check.head()
df_train_transactions_check["_merge"].value_counts()

_merge
both          1384617
left_only           0
right_only          0
Name: count, dtype: int64

In [113]:
df_train_transactions_check[
    df_train_transactions_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order, product_id, add_to_cart_order, reordered, _merge]
Index: []

In [114]:
print(df_orders_train.shape)
print(df_orders_products_train.shape)
print(df_train_transactions.shape)

(131209, 7)
(1384617, 4)
(1384617, 10)

In [115]:
df_train_transactions.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered'],
      dtype='str')

In [118]:
df_train_transactions['order_id'].value_counts()

order_id
2813632    80
1395075    80
949182     77
2869702    76
341238     76
           ..
97844       1
1954863     1
2086546     1
1014278     1
67174       1
Name: count, Length: 131209, dtype: int64

In [124]:
df_train_transactions.groupby("order_id").size().head()

order_id
1      8
36     8
38     9
96     7
98    49
dtype: int64

In [125]:
df_train_transactions.groupby("order_id").size().describe()

count   131,209.00
mean         10.55
std           7.93
min           1.00
25%           5.00
50%           9.00
75%          14.00
max          80.00
dtype: float64

In [128]:
df_train_transactions.groupby("order_dow").size() / df_train_transactions['order_id'].nunique()

order_dow
0   2.47
1   1.57
2   1.22
3   1.18
4   1.18
5   1.35
6   1.58
dtype: float64

In [132]:
df_train_transactions.groupby("order_dow").size()

order_dow
0    324026
1    205978
2    160562
3    154381
4    155481
5    176910
6    207279
dtype: int64

In [133]:
df_train_transactions.groupby("order_hour_of_day")["reordered"].mean()

order_hour_of_day
0    0.57
1    0.58
2    0.58
3    0.58
4    0.60
5    0.62
6    0.65
7    0.65
8    0.64
9    0.62
10   0.61
11   0.59
12   0.59
13   0.59
14   0.59
15   0.58
16   0.59
17   0.59
18   0.58
19   0.59
20   0.60
21   0.61
22   0.60
23   0.59
Name: reordered, dtype: float64

In [136]:
df_train_transactions["product_id"].isna().sum()

np.int64(0)

In [137]:
df_train_analytic = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left"
)

df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,train,11,4,8,14.00,196,1,1,Soda,77.00,7.00,9.00,beverages,soft drinks
1,1187899,1,train,11,4,8,14.00,25133,2,1,Organic String Cheese,21.00,16.00,8.60,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.00,38928,3,1,0% Greek Strained Yogurt,120.00,16.00,12.60,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.00,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.00,17.00,1.00,household,paper goods
4,1187899,1,train,11,4,8,14.00,39657,5,1,Milk Chocolate Almonds,45.00,19.00,6.80,snacks,candy chocolate

In [138]:
df_train_analytic_check = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left",
    indicator=True
)

df_train_analytic_check["_merge"].value_counts()

_merge
both          1384618
left_only          88
right_only          0
Name: count, dtype: int64

In [139]:
df_train_analytic_check[
    df_train_analytic_check["_merge"] == "left_only"
].head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle,_merge
10780,3009052,1629,train,37,0,13,3.00,6799,24,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
52822,195363,7955,train,12,6,14,8.00,6799,4,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
59749,831974,9000,train,11,3,13,20.00,6799,19,0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
64159,206208,9640,train,16,6,11,12.00,6799,6,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
81585,472316,12168,train,10,4,12,0.00,6799,12,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [140]:
df_train_analytic.groupby("department")["reordered"].mean().sort_values(ascending=False)

department
dairy eggs        0.67
produce           0.66
beverages         0.66
bakery            0.63
pets              0.63
deli              0.62
alcohol           0.61
meat seafood      0.59
snacks            0.58
bulk              0.58
breakfast         0.57
frozen            0.56
babies            0.54
dry goods pasta   0.49
canned goods      0.49
household         0.43
other             0.39
missing           0.38
international     0.38
pantry            0.36
personal care     0.34
Name: reordered, dtype: float64

In [141]:
pd.crosstab(
    df_train_analytic["department"],
    df_train_analytic["reordered"]
)

reordered             0       1
department
alcohol            2203    3399
babies             6857    8084
bakery            17702   30692
beverages         38960   75002
breakfast         12654   16898
bulk                573     786
canned goods      24017   22782
dairy eggs        70549  146502
deli              16924   27367
dry goods pasta   19828   18885
frozen            44258   56168
household         20614   15372
international      7380    4522
meat seafood      12400   17907
missing            5103    3148
other              1098     697
pantry            51744   29498
personal care     14309    7290
pets               1663    2834
produce          137201  271886
snacks            49760   69102

In [142]:
pd.crosstab(
    df_train_analytic["order_dow"],
    df_train_analytic["reordered"],
    normalize="index"
)

reordered    0    1
order_dow
0         0.39 0.61
1         0.40 0.60
2         0.41 0.59
3         0.41 0.59
4         0.41 0.59
5         0.39 0.61
6         0.41 0.59

## practise

In [66]:
URL = "https://raw.githubusercontent.com/hovhannisyan91/aca/refs/heads/main/lab/python/data/raw/customers.csv"

In [67]:
import pandas as pd

In [68]:
df = pd.read_csv(URL)
df.to_csv('../data/raw/customers.csv', index= False)

In [69]:
df

,user_id,First Name,Surname,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374
...,...,...,...,...,...,...,...,...,...,...
206204,168073,Lisa,Case,Female,North Carolina,44,4/1/2020,1,married,148828
206205,49635,Jeremy,Robbins,Male,Hawaii,62,4/1/2020,3,married,168639
206206,135902,Doris,Richmond,Female,Missouri,66,4/1/2020,2,married,53374
206207,81095,Rose,Rollins,Female,California,27,4/1/2020,1,married,99799
206208,80148,Cynthia,Noble,Female,New York,55,4/1/2020,1,married,57095

In [70]:
URL = "https://raw.githubusercontent.com/hovhannisyan91/aca/refs/heads/main/lab/python/data/raw/"
l =['customers', 'states']

for i in l:
    df = pd.read_csv(URL + i +'.csv')
    print(df)
    df.to_csv('../data/raw/' + i + '.csv',index=False)
    print(f"{i}.csv is successfully saved")

        user_id First Name   Surname  Gender           STATE  Age date_joined  \
0         26711    Deborah  Esquivel  Female        Missouri   48    1/1/2017
1         33890   Patricia      Hart  Female      New Mexico   36    1/1/2017
2         65803    Kenneth    Farley    Male           Idaho   35    1/1/2017
3        125935   Michelle     Hicks  Female            Iowa   40    1/1/2017
4        130797        Ann   Gilmore  Female        Maryland   26    1/1/2017
...         ...        ...       ...     ...             ...  ...         ...
206204   168073       Lisa      Case  Female  North Carolina   44    4/1/2020
206205    49635     Jeremy   Robbins    Male          Hawaii   62    4/1/2020
206206   135902      Doris  Richmond  Female        Missouri   66    4/1/2020
206207    81095       Rose   Rollins  Female      California   27    4/1/2020
206208    80148    Cynthia     Noble  Female        New York   55    4/1/2020

        n_dependants fam_status  income
0                  3    married  165665
1                  0     single   59285
2                  2    married   99568
3                  0     single   42049
4                  1    married   40374
...              ...        ...     ...
206204             1    married  148828
206205             3    married  168639
206206             2    married   53374
206207             1    married   99799
206208             1    married   57095

[206209 rows x 10 columns]
customers.csv is successfully saved
                   state     region            division
0            Connecticut  Northeast         New England
1                  Maine  Northeast         New England
2          Massachusetts  Northeast         New England
3          New Hampshire  Northeast         New England
4           Rhode Island  Northeast         New England
5                Vermont  Northeast         New England
6             New Jersey  Northeast     Middle Atlantic
7               New York  Northeast     Middle Atlantic
8           Pennsylvania  Northeast     Middle Atlantic
9               Illinois    Midwest  East North Central
10               Indiana    Midwest  East North Central
11              Michigan    Midwest  East North Central
12                  Ohio    Midwest  East North Central
13             Wisconsin    Midwest  East North Central
14                  Iowa    Midwest  West North Central
15                Kansas    Midwest  West North Central
16             Minnesota    Midwest  West North Central
17              Missouri    Midwest  West North Central
18              Nebraska    Midwest  West North Central
19          North Dakota    Midwest  West North Central
20          South Dakota    Midwest  West North Central
21              Delaware      South      South Atlantic
22  District of Columbia      South      South Atlantic
23               Florida      South      South Atlantic
24               Georgia      South      South Atlantic
25              Maryland      South      South Atlantic
26        North Carolina      South      South Atlantic
27        South Carolina      South      South Atlantic
28              Virginia      South      South Atlantic
29         West Virginia      South      South Atlantic
30               Alabama      South  East South Central
31              Kentucky      South  East South Central
32           Mississippi      South  East South Central
33             Tennessee      South  East South Central
34              Arkansas      South  West South Central
35             Louisiana      South  West South Central
36              Oklahoma      South  West South Central
37                 Texas      South  West South Central
38               Arizona       West            Mountain
39              Colorado       West            Mountain
40                 Idaho       West            Mountain
41               Montana       West            Mountain
42                Nevada       West            Mountain
43            New Mexico       West            Mountain
44                  Utah       West            Mountain
45               Wyoming       West            Mountain
46                Alaska       West             Pacific
47            California       West             Pacific
48                Hawaii       West             Pacific
49                Oregon       West             Pacific
50            Washington       West             Pacific
states.csv is successfully saved

In [71]:
import pandas as pd

In [72]:
import pandas as pd
SQL_URL = "https://raw.githubusercontent.com/hovhannisyan91/sql-analytics-portfolio/refs/heads/main/data/public_schema/"
TO_SAVE_URL =  '/Users/User/Desktop/aca/sql-analytics-portfolio/data/public_schema/'
l = ['customers', 'employees','orders','products', 'sales']

for i in l:
    print(100*'-')
    print(f"trying to download {i}.csv")
    df = pd.read_csv(SQL_URL+i+'.csv')
    print(f"{i}.csv is downloaded")
    print(f"the shape of {i}.csv : {df.shape}")
    print(f"trying to save  {i}.csv")
    df.to_csv(TO_SAVE_URL+i+'.csv',index=False)
    print(f"{i}.csv is successfully saved")

----------------------------------------------------------------------------------------------------
trying to download customers.csv
customers.csv is downloaded
the shape of customers.csv : (2000, 5)
trying to save  customers.csv
customers.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download employees.csv
employees.csv is downloaded
the shape of employees.csv : (100, 5)
trying to save  employees.csv
employees.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download orders.csv
orders.csv is downloaded
the shape of orders.csv : (200, 5)
trying to save  orders.csv
orders.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download products.csv
products.csv is downloaded
the shape of products.csv : (100, 5)
trying to save  products.csv
products.csv is successfully saved
----------------------------------------------------------------------------------------------------
trying to download sales.csv
sales.csv is downloaded
the shape of sales.csv : (5000, 8)
trying to save  sales.csv
sales.csv is successfully saved

## Parquet  


pip install pyarrow fastparquet

In [73]:
import pandas as pd

In [74]:
pip install pyarrow fastparquet

Requirement already satisfied: pyarrow in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (24.0.0)
Requirement already satisfied: fastparquet in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (2026.3.0)
Requirement already satisfied: pandas>=1.5.0 in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (from fastparquet) (3.0.1)
Requirement already satisfied: numpy in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (from fastparquet) (2.4.4)
Requirement already satisfied: cramjam>=2.3 in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (from fastparquet) (2026.3.0)
Requirement already satisfied: packaging in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (from fastparquet) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (from pandas>=1.5.0->fastparquet) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\User\anaconda3\envs\myenv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [75]:
import zipfile
with zipfile.ZipFile("../data/raw/order_products_prior.parquet.zip", "r") as zip_ref:   
    zip_ref.extractall("../data/raw/")

In [76]:
import pandas as pd
df_parquet = pd.read_parquet('../data/raw/order_products_prior.parquet')

In [77]:
df_parquet

          order_id  product_id  add_to_cart_order  reordered
0                2       33120                  1          1
1                2       28985                  2          1
2                2        9327                  3          0
3                2       45918                  4          1
4                2       30035                  5          0
...            ...         ...                ...        ...
32434484   3421083       39678                  6          1
32434485   3421083       11352                  7          0
32434486   3421083        4600                  8          0
32434487   3421083       24852                  9          1
32434488   3421083        5020                 10          1

[32434489 rows x 4 columns]