In [19]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 47, 63, 29],
    "income": [18000, 42000, 72000, 95000, 25000]
})

df_customers_dummy

  customer  age  income
0        A   22   18000
1        B   35   42000
2        C   47   72000
3        D   63   95000
4        E   29   25000

In [20]:
import pandas as pd

In [21]:
def age_group_label(age):
    if age >= 60:
        return 'Senior'
    elif age >= 30:
        return 'Middle'
    else:
        return 'Young'
    
age_group_label(60)

'Senior'

In [22]:
df_customers_dummy['age_group_label'] = df_customers_dummy['age'].apply(age_group_label)
df_customers_dummy

  customer  age  income age_group_label
0        A   22   18000           Young
1        B   35   42000          Middle
2        C   47   72000          Middle
3        D   63   95000          Senior
4        E   29   25000           Young

In [ ]:
def income_band(income):
    if income >= 72000:
        return 'High income'
    elif income >= 42000:
        return 'Middle income'
    else:
        return 'Low income'
    
income_band(18000)

In [ ]:
df_customers_dummy['income_band'] = df_customers_dummy['income'].apply(income_band)
df_customers_dummy

In [25]:
income_band(18000)

'Low income'

In [26]:
from utils import age_group_label



df_customers_dummy

  customer  age  income age_group_label
0        A   22   18000           Young
1        B   35   42000          Middle
2        C   47   72000          Middle
3        D   63   95000          Senior
4        E   29   25000           Young